In [4]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df=pd.read_csv('../data/new_dataset.csv')

def get_classification_score(dataset, list_of_features, label, model=svm.SVC(gamma=0.001), dropna=True):
    temp = dataset.copy()
    if dropna:
        temp = temp.dropna()
        
    y = temp.pop(label)
    
    Xtrain, Xtest, ytrain, ytest = train_test_split(temp, y,test_size=0.25, random_state=0)
    
    # Xtrain = Xtrain[list_of_features].values
    # Xtest = Xtest[list_of_features].values
        
    if len(Xtrain.shape) < 2:
        Xtrain = Xtrain.reshape(-1, 1)
        
    if len(Xtest.shape) < 2:
        Xtest = Xtest.reshape(-1, 1)
        
    model.fit(Xtrain,ytrain)

    ypredit = model.predict(Xtest)
    
    print(classification_report(ytest, ypredit))
    print(confusion_matrix(ytest, ypredit))
    return accuracy_score(ytest, ypredit)

def compare_features(
    dataset, 
    list_of_features_1, 
    list_of_features_2,
    label,
    ):
    
    score_1 = get_classification_score(dataset, list_of_features_1, label)
    score_2 = get_classification_score(dataset, list_of_features_2, label)
    
    print(f"Avec les colonnes {list_of_features_1}, le score est de {score_1}.")
    print(f"Avec les colonnes {list_of_features_2}, le score est de {score_2}.")

compare_features(df, ["MTRANS", "Weight", "SMOKE", "CAEC"], ["Weight"], "NObeyesdad")

rf_clf = RandomForestClassifier(
    random_state=77,
    criterion='entropy',    
    max_depth=20,
    class_weight='balanced',    
    n_estimators=700,
)

score_1 = get_classification_score(df, "", "NObeyesdad", rf_clf)
print(score_1)


                     precision    recall  f1-score   support

Insufficient_Weight       0.76      0.95      0.84        78
      Normal_Weight       0.60      0.43      0.50        69
     Obesity_Type_I       0.58      0.49      0.53        86
    Obesity_Type_II       0.98      0.79      0.88        73
   Obesity_Type_III       0.93      1.00      0.96        88
 Overweight_Level_I       0.60      0.57      0.59        68
Overweight_Level_II       0.38      0.50      0.43        66

           accuracy                           0.69       528
          macro avg       0.69      0.68      0.68       528
       weighted avg       0.70      0.69      0.69       528

[[74  4  0  0  0  0  0]
 [23 30  1  0  0 15  0]
 [ 0  0 42  1  2  1 40]
 [ 0  0 10 58  5  0  0]
 [ 0  0  0  0 88  0  0]
 [ 1 11  2  0  0 39 15]
 [ 0  5 18  0  0 10 33]]
                     precision    recall  f1-score   support

Insufficient_Weight       0.76      0.95      0.84        78
      Normal_Weight       0.60    